### PR TITLE
issue #7 UI design added

### PR DESCRIPTION
**Pull request by ronitblenz**
Mention Medium Tag and JWoC tag before merging my PR
Screenshot 2022-02-12 at 12 14 19 PM

https://www.figma.com/file/FMQOuAaw2gmOP2FVE0e1pH/Feature-Card-(Community)?node-id=1%3A2707

UI design made (link provided for further changes if needed)

### CODE REVIEW

**Comment by ZiaCodes** [comment]
> Mention Medium Tag and JWoC tag before merging my PR Screenshot 2022-02-12 at 12 14 19 PM
> 
> https://www.figma.com/file/FMQOuAaw2gmOP2FVE0e1pH/Feature-Card-(Community)?node-id=1%3A2707
> 
> UI design made (link provided for further changes if needed)

Awsome

**Review by ZiaCodes — APPROVED** [review]
@ronitblenz #8

**Comment by ronitblenz** [comment]
You told, it would be a medium issue. isnt it?

**Comment by ZiaCodes** [comment]
> You told, it would be a medium issue. isnt it?

Yes ,if you code this one in reactJs
It was on the easy category , check the issue.

**Comment by ronitblenz** [comment]
I see, then I cant. Its ok🥲

**Comment by ZiaCodes** [comment]
> I see, then I cant. Its ok🥲

No problem , You did a great job Buddy
The design is so cool,. I love it ..
You can work on other issues that need UI Designs , logos and all those things which doesnt require coding ..

**Comment by ronitblenz** [comment]
Yeah sure😇

**Pull request merged**
